### ISSUE TITLE
hunger mechanics may be causing a experience glitch

### ISSUE THREAD

**Issue by boris2255** [CCr4ft3r/appetite#3] opened 2023-01-30 01:51 UTC
been playing a modpack recently hunger mechanics may be causing a problem, every time the hunger bar levels up while you pick up experience it will drastically multiply the experience taken, i am not sure what mod is causing it myself but it happens often with me ending with around 450 levels of experience

**Comment by boris2255** [comment] 2023-01-30 01:52
another problem i began to notice too is the lack of xp loss on death

**Comment by CCr4ft3r** [comment] 2023-01-30 15:58
What a shitty bug - will be fixed asap

**Comment by boris2255** [comment] 2023-02-05 14:33
sorry for taking some time, im not quite sure whats causing the error sadly, best i can do is pass you the entire modpack

**Comment by boris2255** [comment] 2023-02-05 14:33
it may be an incopatibility with another mod? i have no clue

**Comment by boris2255** [comment] 2023-02-05 14:35
heres the modpack https://cdn.discordapp.com/attachments/1052019123225370715/1064028363032887296/Project_Mega_Evol_Delta-trail_1.0.zip

**Comment by CCr4ft3r** [comment] 2023-02-05 14:45
Thank you - I will take a look at it

**Comment by boris2255** [comment] 2023-02-15 18:43
> 

any new updates to the issue?

**Comment by CCr4ft3r** [comment] 2023-02-15 19:15
Sorry for the delay - I'll try to find the cause this week

**Comment by CCr4ft3r** [comment] 2023-02-15 21:23
It's seems to be related to the advancement of Appetite. Even though the advancement is not giving experience points itself. Minecrafts algorithm is giving experience levels after giving experience points even though if it's zero points. I've just tested your modpack but I only get 3 additional levels after the hunger bar leveled up. Can you please provide further information?

- What config values are using for Appetite's Hunger Leveling feature?
- Which level did you had before the hunger bar leveled up and which did you had after it?

**Comment by boris2255** [comment] 2023-02-16 01:59
> It's seems to be related to the advancement of Appetite. Even though the advancement is not giving experience points itself. Minecrafts algorithm is giving experience levels after giving experience points even though if it was zero points. I've just tested your modpack but I only get 3 additional levels after the hunger bar leveled up. Can you please provide further information?
> 
> * What config values are using for Appetite's Hunger Leveling feature?
> * Which level did you had before the hunger bar leveled up and which did you had after it?
> * Which objects, mobs, actions or items did you get expierence from that triggered the advancement of Appetite?

> *first i was using the normal config values the hungry one
> * then the level thing seems to somehow stack with the higher level you are, lets say for example 10
> * killing mobs  in more common chance the datapack https://www.curseforge.com/minecraft/texture-packs/skeluns-xp-reward-system

**Comment by CCr4ft3r** [comment] 2023-02-17 16:27
Fixed in v1.5.1

**Closed by CCr4ft3r** 2023-02-17 16:27 UTC
Labels: bug
